//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheListeningHand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class availability
    {
        public long id { get; set; }
        public Nullable<int> stylistId { get; set; }
        public Nullable<int> dayId { get; set; }
        public Nullable<int> starttime { get; set; }
        public Nullable<int> time { get; set; }
    }
}
