//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheListeningHand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class day
    {
        public long id { get; set; }
        public string day1 { get; set; }
    }
}
